# Generated by Django 4.1.7 on 2023-03-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='whatsapp',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
