# Generated by Django 4.1.7 on 2023-03-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_settings_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='address',
            field=models.CharField(default=1, max_length=44),
            preserve_default=False,
        ),
    ]
