# Generated by Django 4.1.7 on 2023-03-02 01:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactus_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='about_use',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
