# Generated by Django 4.1.7 on 2023-03-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
