# Generated by Django 4.1.7 on 2023-03-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_banners_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name': 'بنر', 'verbose_name_plural': 'بنرها'},
        ),
        migrations.AddField(
            model_name='banners',
            name='state',
            field=models.IntegerField(choices=[(0, 'Top Banner'), (1, 'Side Banner')], default=0),
        ),
    ]
