# Generated by Django 4.1.7 on 2023-03-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Video')], default=0),
        ),
    ]
