# Generated by Django 4.1.7 on 2023-03-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Video'), (2, 'Picture')], default=0),
        ),
    ]
